"""unique short url

Revision ID: ea68b781d75b
Revises: 85654d7c787f
Create Date: 2024-10-25 17:41:59.919125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea68b781d75b'
down_revision: Union[str, None] = '85654d7c787f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urls_short_url', table_name='urls')
    op.create_index(op.f('ix_urls_short_url'), 'urls', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_url'), table_name='urls')
    op.create_index('ix_urls_short_url', 'urls', ['short_url'], unique=False)
    # ### end Alembic commands ###
